// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./Theme";

/**
 * The app's ENTIRE persisted shape -- exactly two keys, by design (D11-04
 * scope discipline). Adding a third key (window geometry, last-selected
 * category, sort-column, ...) is explicitly out of scope for this phase --
 * see 11-CONTEXT.md's Phase Boundary.
 */
export type AppSettings = { language: string, theme: Theme, };
