// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single browse-list row over IPC to the frontend — the ONE unified row
 * type every category (Notes, Bookmarks, Annotations, Favorites, Highlights,
 * Playlists) collapses to (D6-02). Field shape mirrors the columns the Python
 * getters produce after `merge_df` (`Id`, `Language`, `Symbol`, `Color`,
 * `Tags`, `Modified`, `Year`, `Detail1`, `Detail2`, `Short`, `Full`, `Type`).
 *
 * The nullable columns are the `merge_df` `fill_null` analog: a category that
 * does not produce a column leaves it `None` (Bookmarks/Annotations/Favorites
 * have no color/tags/modified; Playlists has no language). Notes populates
 * every column, so it wraps each value in `Some(...)` — byte-identical to the
 * pre-refactor `NotesRow`. `short`/`full`/`type_group` are always filled by
 * `merge_df` (even for Playlists), so they stay non-optional.
 */
export type BrowseRow = { id: bigint, 
/**
 * UI language name, or `None` for a category without a language column
 * (e.g. Playlists). Notes always sets `Some(...)`.
 */
language: string | null, 
/**
 * Processed publication code/symbol (`process_code` output), or
 * `"* OTHER *"` when empty — never the raw `KeySymbol`.
 */
symbol: string, 
/**
 * English color name (`process_color`), or `None` for a category with no
 * color column (e.g. Bookmarks/Favorites). i18n is out of scope for
 * Phase 1 (UI-SPEC defers locale switching to Phase 11).
 */
color: string | null, 
/**
 * Concatenated tag names, or `None` for a category that has no tags.
 */
tags: string | null, 
/**
 * Last-modified date, or `None` for a category without a modified column.
 */
modified: string | null, year: string | null, detail1: string | null, detail2: string | null, short: string, full: string, type_group: string, 
/**
 * True for independent notes (`LocationId IS NULL`) — surfaced so the
 * frontend can render the `* INDEPENDENT *` affordance without
 * re-deriving it from `type_group`. Only Notes sets this true.
 */
independent: boolean, };
