// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NonEmptyBlockRangeIds } from "./NonEmptyBlockRangeIds";
import type { NonEmptyNoteIds } from "./NonEmptyNoteIds";

/**
 * The recolor target: which category's selection, carrying that category's
 * own typed non-empty identity-PK wrapper. A tagged enum rather than a bare
 * `Vec<i64>` + separate `Category` field so the empty-selection-
 * unrepresentable guarantee (SAFE-03) holds per category at IPC
 * deserialization — a `Highlights` selection of `BlockRangeId`s and a
 * `Notes` selection of `NoteId`s are never interchangeable, and neither can
 * ever be empty.
 */
export type ColorSelection = { "category": "Highlights", ids: NonEmptyBlockRangeIds, } | { "category": "Notes", ids: NonEmptyNoteIds, };
