// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * General semantic preview report: per-table primary-key counts of rows
 * newly present (`added`), present in both before/after snapshots
 * (`overwritten` — e.g. the TagMap re-densify's preserved mappings, or
 * `Location.Title` normalized to `''`), and genuinely removed (`deleted`).
 * Intentionally GENERAL (not Notes-delete-specific) so Phase 4 (schema
 * downgrade preview) and Phase 5 (merge preview) can reuse it unchanged
 * (D2-07).
 */
export type DryRunReport = { added: { [key in string]: number }, overwritten: { [key in string]: number }, deleted: { [key in string]: number }, total_deleted: number, };
