// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sanitized, `Serialize`-able error that crosses the Tauri IPC boundary.
 * Never includes a raw absolute path or the wrapped source error's Display.
 */
export type ErrorDto = { code: string, operation: string, safe_file_name: string | null, message_key: string, };
