// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The minimal identifying fields needed to mark a Favorite: the edition's
 * `KeySymbol` and integer `MepsLanguage` id — exactly what
 * [`apply_favorite_add`]'s `Location` find-or-insert and duplicate check
 * need. Deliberately NOT the full
 * [`crate::db::resources::FavoriteEdition`] catalog row: per T-07-02 no
 * table/column name crosses the IPC boundary, and the frontend only ever
 * needs to send back these two typed fields (taken from whichever
 * `FavoriteEdition` row the user picked) — never the display-only
 * `short`/`lang` strings, which the mutation itself doesn't use.
 */
export type FavoriteEditionRef = { symbol: string, language: bigint, };
