// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One row of the bundled `Favorites` VIEW (columns `Language, Symbol,
 * Short, Lang` — 07-RESEARCH.md Corrections item 1: there is no
 * `favorites` table, only this VIEW over `Publications`/`Extras`). A
 * Bible-edition catalog entry the Favorite Dialog's edition picker renders
 * (07-01-PLAN.md Task 2/3, EDIT-05 mark).
 *
 * `language` is the integer `MepsLanguage` id (goes into
 * `Location.MepsLanguage` when marking) and `symbol` is the edition's
 * `KeySymbol` (goes into `Location.KeySymbol` and the `TagMap` duplicate
 * check) — both are what [`crate::db::favorites::apply_favorite_add`]
 * actually needs. `short` and `lang` are DISPLAY-ONLY strings (`short` =
 * edition short title shown in the edition list; `lang` = the display
 * language name, e.g. `"English"` — what [`ResourceCatalog::load_favorite_editions`]
 * filters by, NOT the integer `language` field despite the similar name).
 */
export type FavoriteEdition = { language: bigint, symbol: string, short: string, lang: string, };
