// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Tauri-facing result of an incremental export (IO-04) — export scope
 * counts, NOT a mutation preview (this phase never mutates the archive, so
 * it is a new DTO rather than a reuse of `db::edit::DryRunReport`, which
 * that shipped shape's own doc reserves for edit-op previews).
 * `deleted_candidates` is informational only (D9-04): the frontend must
 * render it with an explicit caveat that removals are never written to the
 * output file.
 */
export type IncrementalExportSummary = { added: number, modified: number, deleted_candidates: number, exported: number, };
