// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Internal jwlCore load-path error (01-03, D-12/D-13). Reserved for
 * genuinely unexpected load faults — the arm64-windows "no binary" and
 * other unsupported-platform cases are NOT represented here; they surface
 * as a non-loaded `JwlCoreStatus` (Ok, not Err) at the command boundary
 * per finding 12.
 */
export type JwlCoreError = { "LoadFailed": { reason: string, } } | { "MissingSymbol": { symbol: string, } } | "PathResolutionFailed";
