// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Unified status shape returned by `check_jwlcore` (finding 12). A missing
 * or wrong-arch binary is represented as `loaded: false` with a `reason` —
 * this is an `Ok` value, never an `Err`. `Err(JwlCoreError)` is reserved for
 * a genuinely unexpected load fault (e.g. a present-but-corrupt binary).
 */
export type JwlCoreStatus = { loaded: boolean, arch: string, version: string | null, reason: string | null, };
