// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Tauri-facing result of [`media_add_apply`] — how many of the
 * (already-precheck-filtered-to-New) files were actually added. A copy
 * failure is a WHOLE-BATCH failure (PD-3, this app's first staged-DB-then-
 * files commit) — it never partially lands, so there is no per-file
 * "failed" count here; the frontend derives its per-row "added"/"skipped"/
 * "unreadable" glyphs from the PRECHECK response plus this success/failure
 * outcome, never a third, separate per-file apply result.
 */
export type MediaAddApplyReport = { added: number, };
