// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Tauri-facing DTO for one [`MediaPrecheck`] row — `status` is one of
 * `"new"` / `"duplicate"` / `"unsupported"`, `reason` is set only for
 * `"unsupported"` (the UI-SPEC's per-file rejection text).
 */
export type MediaPrecheckResult = { path: string, status: string, reason: string | null, };
