// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty selection of `Bookmark.BookmarkId` values — the Bookmarks
 * identity PK (`browse.rs:33-37`, NOT the first-SELECTed `LocationId` — the
 * load-bearing pitfall this phase's research called out). Constructed only
 * via `TryFrom<Vec<i64>>`/serde's `try_from` container attribute, mirroring
 * [`NonEmptyNoteIds`] exactly.
 */
export type NonEmptyBookmarkIds = Array<bigint>;
