// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Typed non-empty `PlaylistItemId` selection for export — same D7-01 shape
 * as [`crate::db::favorites::NonEmptyTagMapIds`].
 */
export type NonEmptyPlaylistItemIds = Array<bigint>;
