// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty selection of Annotation `LocationId` values — the browse-list
 * Annotations identity (`browse.rs:28-31`). Deleting by `LocationId`
 * removes ALL `InputField` rows at that location — an INTENTIONAL
 * over-deletion (rule #10, `JWLManager.py:3669`), distinct from the
 * record-editor's own `(LocationId, TextTag)`-scoped single delete
 * (`crate::db::record_edit::apply_record_delete`). The two paths must never
 * be crossed.
 */
export type NonEmptyLocationIds = Array<bigint>;
