// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty selection of `Note.NoteId` values. Constructed only via
 * `TryFrom<Vec<i64>>`/`serde`'s `try_from` container attribute, which
 * rejects an empty `Vec` — an empty selection is impossible by
 * construction, not merely a runtime-checked precondition (SAFE-03, D2-06).
 * The `Note.NoteId` type is `i64`, so ids are always bound as typed
 * integers, never string-interpolated (SAFE-02) — see [`delete_notes`].
 */
export type NonEmptyNoteIds = Array<bigint>;
