// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty selection of `BlockRange.BlockRangeId` values — the Highlights
 * identity PK (`db::browse::query_highlights`, `browse.rs:47-52`). Shared by
 * Highlights recolor (this module) and Highlights delete
 * (`db::delete::delete_highlights`), which imports this type rather than
 * defining a second identical wrapper. Constructed only via
 * `TryFrom<Vec<i64>>`/`serde`'s `try_from` container attribute — an empty
 * selection is impossible by construction, mirroring
 * `db::favorites::NonEmptyTagMapIds` exactly.
 */
export type NonEmptyBlockRangeIds = Array<bigint>;
