// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A non-empty selection of `TagMap.TagMapId` values identifying Favorite
 * rows to unmark (`db::browse::query_favorites`: a Favorite's identity PK
 * is `TagMapId`, the row's `NoteId IS NULL`). Constructed only via
 * `TryFrom<Vec<i64>>`/`serde`'s `try_from` container attribute, which
 * rejects an empty `Vec` — an empty selection is impossible by
 * construction, not merely a runtime-checked precondition, mirroring
 * `db::delete::NonEmptyNoteIds` (`delete.rs:48-85`) exactly.
 */
export type NonEmptyTagMapIds = Array<bigint>;
