// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DryRunReport } from "./DryRunReport";

/**
 * The Tauri-facing result of a Notes import preview (IO-02, D8-09) — the
 * standard [`DryRunReport`] PLUS the file's own detected bucket-delete
 * character (if any), so the frontend can render the Notes-only extra
 * preview clause and require an explicit opt-in BEFORE calling
 * [`import_notes_apply`] with that same character. `report` already
 * reflects what would happen if `bucket` were applied — this preview runs
 * [`dry_run_import_notes`] with the FILE's own bucket (never a caller-
 * supplied one, since there is no caller opt-in yet at preview time), all
 * inside a transaction that is never committed (SAFE-01) — showing the true
 * effect is harmless because nothing is ever persisted from a dry run.
 */
export type NotesImportPreview = { report: DryRunReport, bucket: string | null, };
