// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single Notes-list row, over IPC to the frontend.
 */
export type NotesRow = { id: bigint, color_index: bigint, tags: string | null, modified: string | null, };
