// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single Notes-list row, over IPC to the frontend. Field shape mirrors
 * the columns `get_notes`/`load_independent` produce after `merge_df`
 * (`Id`, `Language`, `Symbol`, `Color`, `Tags`, `Modified`, `Year`,
 * `Detail1`, `Detail2`, `Short`, `Full`, `Type`).
 */
export type NotesRow = { id: bigint, language: string, 
/**
 * Processed publication code/symbol (`process_code` output), or
 * `"* OTHER *"` when empty — never the raw `KeySymbol`.
 */
symbol: string, 
/**
 * English color name (`process_color`); i18n is out of scope for
 * Phase 1 (UI-SPEC defers locale switching to Phase 11).
 */
color: string, tags: string, modified: string, year: string | null, detail1: string | null, detail2: string | null, short: string, full: string, type_group: string, 
/**
 * True for independent notes (`LocationId IS NULL`) — surfaced so the
 * frontend can render the `* INDEPENDENT *` affordance without
 * re-deriving it from `type_group`.
 */
independent: boolean, };
