// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DryRunReport } from "./DryRunReport";

/**
 * The Tauri-facing result of a Playlist import preview (IO-02, 08-05-PLAN.md)
 * — the standard [`DryRunReport`] PLUS the playlist's name and its media
 * file count, so the frontend can render the leading UI-SPEC clause *"This
 * adds the playlist "{Name}" and its {N} media file{s}."* before the
 * standard added/updated/skipped lines.
 */
export type PlaylistImportPreview = { report: DryRunReport, playlist_name: string, media_count: number, };
