// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of [`export_playlist`]: the number of `PlaylistItem` rows actually
 * copied, plus any best-effort media-copy warnings (a missing source media
 * file never aborts the export, matching Python's `try/except` around
 * `shutil.copy2`).
 */
export type PlaylistExportReport = { item_count: number, warnings: Array<string>, };
