// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DryRunReport } from "./DryRunReport";

/**
 * The Tauri-facing report for BOTH the media-delete dry-run and apply: the
 * standard [`DryRunReport`] plus the two D8-07 counts the UI-SPEC's
 * "shared media survives" summary needs — `media_removed` (files whose
 * `IndependentMedia` row was deleted) and `media_kept` (files evaluated but
 * kept because a surviving item still references them).
 */
export type PlaylistDeleteReport = { report: DryRunReport, media_removed: number, media_kept: number, };
