// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The current field values for one record, fetched fresh when the editor
 * opens. `BrowseRow` (the category list's row shape) never carries a Note's
 * `Title`/`Content` or an Annotation's `Value` — those are the browse list's
 * publication-LABEL metadata, not the record's own editable content —
 * mirroring the Python Data Viewer's own separate `get_notes()`/
 * `get_annotations()` fetch (`JWLManager.py:3041`, `:3125`) rather than
 * reusing the browse-list row.
 */
export type RecordEditFields = { "category": "Notes", title: string, content: string, 
/**
 * `None` when the Note has no linked `UserMark` yet (`UserMarkId IS
 * NULL`) — the editor's "No color" affordance (07-UI-SPEC.md
 * partial-state).
 */
color_index: bigint | null, } | { "category": "Annotations", value: string, };
