// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The typed, field-constrained edit payload IPC accepts — Notes: `Title`/
 * `Content`/`ColorIndex`; Annotations: `Value` only. No table name, column
 * name, or SQL fragment ever crosses this boundary (D7-09).
 */
export type RecordEditPayload = { "category": "Notes", note_id: bigint, title: string, content: string, 
/**
 * `None` leaves the Note's color untouched; `Some(idx)` sets it,
 * synthesizing a `UserMark` first if the Note has none yet.
 */
color_index: bigint | null, } | { "category": "Annotations", location_id: bigint, text_tag: string, value: string, };
