// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Identifies exactly one record for [`fetch_record_fields`] and
 * [`apply_record_delete`] — the record-editor's own scoped identity, kept
 * distinct from the browse-list's per-category identity types in
 * `db::delete` (a Note's `NoteId` here is the SAME value as
 * `db::delete::NonEmptyNoteIds`, but this type carries exactly one id, never
 * a selection).
 */
export type RecordIdentity = { "category": "Notes", note_id: bigint, } | { "category": "Annotations", location_id: bigint, text_tag: string, };
