// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One `Tag WHERE Type = 1` row's tri-state count for a given note
 * selection — `count == 0` (unchecked), `count == selection.len()`
 * (checked), otherwise indeterminate. Ports `get_notes`'s per-tag SUM
 * (`JWLManager.py:3287-3300`). The frontend derives the checkbox
 * tri-state purely from `count` vs. the selection size it already knows —
 * no separate boolean flags cross the IPC boundary.
 */
export type TagState = { tag_id: bigint, name: string, count: bigint, };
