// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The two supported themes (D11-03). Serialized lowercase so the JSON file
 * and the frontend's `data-theme` attribute value read identically
 * (`"light"`/`"dark"`).
 */
export type Theme = "light" | "dark";
